name: PR Verifier

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

permissions:
  pull-requests: read

jobs:
  verify-pr-title:
    uses: rossoctl/.github/.github/workflows/pr-verifier-required.yml@2998dc5dad9543800d42ffb14cdcb7506e82cb8d # main, 2026-07-28
